# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'
    
env:
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup WARP
        uses: fscarmen/warp-on-actions@v1.1
      - name: Run a one-line script
        run: |
          bash cb.sh
          #sudo warp-cli --accept-tos mode proxy
          sleep 10
          bash panda.sh
          bash st.sh
        env:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
          BOTTOKEN: ${{ secrets.BOTTOKEN }}
          SYNCTV: ${{ secrets.SYNCTV }}
          COOKIE: ${{ secrets.COOKIE }}
          USERTOKEN: ${{ secrets.USERTOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          M3U8SITE: ${{ secrets.M3U8SITE }}
      - name: commit
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "update" -a
      - name: Push changes
        id: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Retry Push on Failure
        if: failure()
        run: |
          git push
