# This is a basic workflow to help you get started with Actions

name: Ckeck

# Controls when the workflow will run
on:
  workflow_dispatch:
#  schedule:
#    - cron: '*/30 * * * *'
    
env:
  TZ: Asia/Shanghai
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup WARP
        uses: fscarmen/warp-on-actions@v1.1
      - name: Run a one-line script
        run: |
          curl ip.sb
        env:
          AUTHORIZATION: ${{ secrets.AUTHORIZATION }}
          BOTTOKEN: ${{ secrets.BOTTOKEN }}
          SYNCTV: ${{ secrets.SYNCTV }}
          COOKIE: ${{ secrets.COOKIE }}
          USERTOKEN: ${{ secrets.USERTOKEN }}
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
      - name: disconnect warp
        run: |
          warp-cli --accept-tos disconnect
          curl ip.sb
      - name: commit
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git add .
          git commit -m "update" -a
        continue-on-error: true
      - name: Push changes
        id: push
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true
      - name: Retry Push on Failure
        if: failure()
        run: |
          git push
